### ISSUE TITLE
further nesting for credentials

### ISSUE THREAD

**Issue by ansuz** [hyperboria/peers#76]
The js api recurses over the directory structure, finding keys, and exposing everything as a searchable JSON structure.

Now that this api is being used by [a queryable http api](https://github.com/fc00/peers-api), it's apparent that this repo could benefit from a further nested structure.

`/<continent>/<country>/<region>/<city>/<neighbourhood>/credential.k` would expose more search terms that users could employ to find nearby nodes.

**Comment by cschmittiey** [comment]
While more info is always great for finding closer peers, what about those
people who might not want to volunteer data that precise? For instance, I'm
happy to volunteer I live in Virginia, but I don't usually mention where.

**Comment by ansuz** [comment]
It could be optional, but in any case the public node would only work if an IP is provided.
People can find where _your node_ is already (not _you_), this would only improve discoverability of nodes which are intended to be public anyway.

**Comment by cschmittiey** [comment]
Fair enough. +1 for further nesting.

On Sat, Oct 1, 2016, 7:10 AM ansuz <notifications@github.com> wrote:

It could be optional, but in any case the public node would only work if an
IP is provided.
People can find where *your node* is already (not *you*), this would only
improve discoverability of nodes which are intended to be public anyway.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/hyperboria/peers/issues/76#issuecomment-250906726>, or mute
the thread
